define( function( require, exports, module ) {
	var data = [{id: 'D11A', name:'1-1 初战贼军'},
	            {id: 'D11B', name:'1-1 初战贼军'},
	            {id: 'D11C', name:'1-1 初战贼军'},
	            {id: 'D13A', name:'1-2 张宝护卫'},
	            {id: 'D13B', name:'1-2 张宝护卫'},
	            {id: 'D13C', name:'1-2 张宝护卫'},
	            {id: 'D14A', name:'1-3 地公张宝'},
	            {id: 'D14B', name:'1-3 地公张宝'},
	            {id: 'D14C', name:'1-3 地公张宝'},
	            {id: 'D15A', name:'1-4 程远志大军'},
	            {id: 'D15B', name:'1-4 程远志大军'},
	            {id: 'D15C', name:'1-4 程远志大军'},
	            {id: 'D16A', name:'1-5 天公张角'},
	            {id: 'D16B', name:'1-5 天公张角'},
	            {id: 'D16C', name:'1-5 天公张角'},
	            {id: 'D21A', name:'2-1 魔军突袭'},
	            {id: 'D21B', name:'2-1 魔军突袭'},
	            {id: 'D21C', name:'2-1 魔军突袭'},
	            {id: 'D22A', name:'2-2 伏击张济'},
	            {id: 'D22B', name:'2-2 伏击张济'},
	            {id: 'D22C', name:'2-2 伏击张济'},
	            {id: 'D23A', name:'2-3 驰援孙坚'},
	            {id: 'D23B', name:'2-3 驰援孙坚'},
	            {id: 'D23C', name:'2-3 驰援孙坚'},
	            {id: 'D24A', name:'2-4 重甲魔军'},
	            {id: 'D24B', name:'2-4 重甲魔军'},
	            {id: 'D24C', name:'2-4 重甲魔军'},
	            {id: 'D25A', name:'2-5 魔军再袭'},
	            {id: 'D25B', name:'2-5 魔军再袭'},
	            {id: 'D25C', name:'2-5 魔军再袭'},
	            {id: 'D26A', name:'2-6 西凉骑兵'},
	            {id: 'D26B', name:'2-6 西凉骑兵'},
	            {id: 'D26C', name:'2-6 西凉骑兵'},
	            {id: 'D31A', name:'3-1 魔军力士'},
	            {id: 'D31B', name:'3-1 魔军力士'},
	            {id: 'D31C', name:'3-1 魔军力士'},
	            {id: 'D32A', name:'3-2 牛辅飞熊军'},
	            {id: 'D32B', name:'3-2 牛辅飞熊军'},
	            {id: 'D32C', name:'3-2 牛辅飞熊军'},
	            {id: 'D33A', name:'3-3 三英战吕布'},
	            {id: 'D33B', name:'3-3 三英战吕布'},
	            {id: 'D33C', name:'3-3 三英战吕布'},
	            {id: 'D34A', name:'3-5 山中埋伏'},
	            {id: 'D34B', name:'3-5 山中埋伏'},
	            {id: 'D34C', name:'3-5 山中埋伏'},
	            {id: 'D35A', name:'3-6 魔君董卓'},
	            {id: 'D35B', name:'3-6 魔君董卓'},
	            {id: 'D35C', name:'3-6 魔君董卓'},
	            {id: 'D41A', name:'4-1 江东暗战'},
	            {id: 'D41B', name:'4-1 江东暗战'},
	            {id: 'D41C', name:'4-1 江东暗战'},
	            {id: 'D42A', name:'4-2 锦帆营水军'},
	            {id: 'D42B', name:'4-2 锦帆营水军'},
	            {id: 'D42C', name:'4-2 锦帆营水军'},
	            {id: 'D43A', name:'4-3 战船神威'},
	            {id: 'D43B', name:'4-3 战船神威'},
	            {id: 'D43C', name:'4-3 战船神威'},
	            {id: 'D44A', name:'4-4 霸主水鬼王'},
	            {id: 'D44B', name:'4-4 霸主水鬼王'},
	            {id: 'D44C', name:'4-4 霸主水鬼王'},
	            {id: 'D45A', name:'4-5 神秘水怪'},
	            {id: 'D45B', name:'4-5 神秘水怪'},
	            {id: 'D45C', name:'4-5 神秘水怪'},
	            {id: 'D46A', name:'4-6 卷浪水师'},
	            {id: 'D46B', name:'4-6 卷浪水师'},
	            {id: 'D46C', name:'4-6 卷浪水师'},
	            {id: 'D47A', name:'4-7 威勇夏侯渊'},
	            {id: 'D47B', name:'4-7 威勇夏侯渊'},
	            {id: 'D47C', name:'4-7 威勇夏侯渊'},
	            {id: 'D51A', name:'5-1 水中精怪'},
	            {id: 'D51B', name:'5-1 水中精怪'},
	            {id: 'D51C', name:'5-1 水中精怪'},
	            {id: 'D52A', name:'5-2 卷浪元帅'},
	            {id: 'D52B', name:'5-2 卷浪元帅'},
	            {id: 'D52C', name:'5-2 卷浪元帅'},
	            {id: 'D53A', name:'5-4 封炎*天机'},
	            {id: 'D53B', name:'5-4 封炎*天机'},
	            {id: 'D53C', name:'5-4 封炎*天机'},
	            {id: 'D54A', name:'5-5 封炎*天璇'},
	            {id: 'D54B', name:'5-5 封炎*天璇'},
	            {id: 'D54C', name:'5-5 封炎*天璇'},
	            {id: 'D55A', name:'5-6 炎帝残兵'},
	            {id: 'D55B', name:'5-6 炎帝残兵'},
	            {id: 'D55C', name:'5-6 炎帝残兵'},
	            {id: 'D56A', name:'5-7 八爪妖灵'},
	            {id: 'D56B', name:'5-7 八爪妖灵'},
	            {id: 'D56C', name:'5-7 八爪妖灵'},
	            {id: 'D61A', name:'6-1 龙啸营先锋'},
	            {id: 'D61B', name:'6-1 龙啸营先锋'},
	            {id: 'D61C', name:'6-1 龙啸营先锋'},
	            {id: 'D62A', name:'6-2 龙啸营步兵'},
	            {id: 'D62B', name:'6-2 龙啸营步兵'},
	            {id: 'D62C', name:'6-2 龙啸营步兵'},
	            {id: 'D63A', name:'6-3 虎将袁胤'},
	            {id: 'D63B', name:'6-3 虎将袁胤'},
	            {id: 'D63C', name:'6-3 虎将袁胤'},
	            {id: 'D64A', name:'6-4 重戟甲兵'},
	            {id: 'D64B', name:'6-4 重戟甲兵'},
	            {id: 'D64C', name:'6-4 重戟甲兵'},
	            {id: 'D65A', name:'6-5 袁术中军'},
	            {id: 'D65B', name:'6-5 袁术中军'},
	            {id: 'D65C', name:'6-5 袁术中军'},
	            {id: 'D66A', name:'6-6 骁将张勋'},
	            {id: 'D66B', name:'6-6 骁将张勋'},
	            {id: 'D66C', name:'6-6 骁将张勋'},
	            {id: 'D71A', name:'7-1 虎豹骑兵'},
	            {id: 'D71B', name:'7-1 虎豹骑兵'},
	            {id: 'D71C', name:'7-1 虎豹骑兵'},
	            {id: 'D72A', name:'7-2 恶来典韦'},
	            {id: 'D72B', name:'7-2 恶来典韦'},
	            {id: 'D72C', name:'7-2 恶来典韦'},
	            {id: 'D73A', name:'7-3 封炎*天枢'},
	            {id: 'D73B', name:'7-3 封炎*天枢'},
	            {id: 'D73C', name:'7-3 封炎*天枢'},
	            {id: 'D74A', name:'7-4 封炎*天权'},
	            {id: 'D74B', name:'7-4 封炎*天权'},
	            {id: 'D74C', name:'7-4 封炎*天权'},
	            {id: 'D75A', name:'7-5 并州铁骑'},
	            {id: 'D75B', name:'7-5 并州铁骑'},
	            {id: 'D75C', name:'7-5 并州铁骑'},
	            {id: 'D76A', name:'7-6 狼鹰骑兵'},
	            {id: 'D76B', name:'7-6 狼鹰骑兵'},
	            {id: 'D76C', name:'7-6 狼鹰骑兵'},
	            {id: 'D77A', name:'7-7 风妖舞魅'},
	            {id: 'D77B', name:'7-7 风妖舞魅'},
	            {id: 'D77C', name:'7-7 风妖舞魅'},
	            {id: 'D81A', name:'8-1 下邳斥候'},
	            {id: 'D81B', name:'8-1 下邳斥候'},
	            {id: 'D81C', name:'8-1 下邳斥候'},
	            {id: 'D82A', name:'8-2 魔军散兵'},
	            {id: 'D82B', name:'8-2 魔军散兵'},
	            {id: 'D82C', name:'8-2 魔军散兵'},
	            {id: 'D83A', name:'8-3 猛将张辽'},
	            {id: 'D83B', name:'8-3 猛将张辽'},
	            {id: 'D83C', name:'8-3 猛将张辽'},
	            {id: 'D84A', name:'8-5 鬼斧强兵'},
	            {id: 'D84B', name:'8-5 鬼斧强兵'},
	            {id: 'D84C', name:'8-5 鬼斧强兵'},
	            {id: 'D85A', name:'8-6 吕布亲卫'},
	            {id: 'D85B', name:'8-6 吕布亲卫'},
	            {id: 'D85C', name:'8-6 吕布亲卫'},
	            {id: 'D86A', name:'8-7 战神吕布'},
	            {id: 'D86B', name:'8-7 战神吕布'},
	            {id: 'D86C', name:'8-7 战神吕布'},
	            {id: 'D91A', name:'9-1 巡山魔军'},
	            {id: 'D91B', name:'9-1 巡山魔军'},
	            {id: 'D91C', name:'9-1 巡山魔军'},
	            {id: 'D92A', name:'9-2 山贼李狗蛋'},
	            {id: 'D92B', name:'9-2 山贼李狗蛋'},
	            {id: 'D92C', name:'9-2 山贼李狗蛋'},
	            {id: 'D93A', name:'9-3 封炎*玉衡'},
	            {id: 'D93B', name:'9-3 封炎*玉衡'},
	            {id: 'D93C', name:'9-3 封炎*玉衡'},
	            {id: 'D94A', name:'9-4 封炎*瑶光'},
	            {id: 'D94B', name:'9-4 封炎*瑶光'},
	            {id: 'D94C', name:'9-4 封炎*瑶光'},
	            {id: 'D95A', name:'9-5 添翼营勇士'},
	            {id: 'D95B', name:'9-5 添翼营勇士'},
	            {id: 'D95C', name:'9-5 添翼营勇士'},
	            {id: 'D96A', name:'9-6 许褚卫队'},
	            {id: 'D96B', name:'9-6 许褚卫队'},
	            {id: 'D96C', name:'9-6 许褚卫队'},
	            {id: 'D97A', name:'9-7 虎痴许褚'},
	            {id: 'D97B', name:'9-7 虎痴许褚'},
	            {id: 'D97C', name:'9-7 虎痴许褚'},
	            {id: 'E01A', name:'10-1 幽冥小鬼'},
	            {id: 'E01B', name:'10-1 幽冥小鬼'},
	            {id: 'E01C', name:'10-1 幽冥小鬼'},
	            {id: 'E02A', name:'10-2 炎族亡魂'},
	            {id: 'E02B', name:'10-2 炎族亡魂'},
	            {id: 'E02C', name:'10-2 炎族亡魂'},
	            {id: 'E03A', name:'10-3 浴火炎凤'},
	            {id: 'E03B', name:'10-3 浴火炎凤'},
	            {id: 'E03C', name:'10-3 浴火炎凤'},
	            {id: 'E04A', name:'10-4 狂暴弃兵'},
	            {id: 'E04B', name:'10-4 狂暴弃兵'},
	            {id: 'E04C', name:'10-4 狂暴弃兵'},
	            {id: 'E05A', name:'10-5 噬魂怨灵'},
	            {id: 'E05B', name:'10-5 噬魂怨灵'},
	            {id: 'E05C', name:'10-5 噬魂怨灵'},
	            {id: 'E06A', name:'10-6 炽火炎兵'},
	            {id: 'E06B', name:'10-6 炽火炎兵'},
	            {id: 'E06C', name:'10-6 炽火炎兵'},
	            {id: 'E07A', name:'10-7 战鬼吕布'},
	            {id: 'E07B', name:'10-7 战鬼吕布'},
	            {id: 'E07C', name:'10-7 战鬼吕布'},
	            {id: 'E11A', name:'11-1 雪域密探'},
	            {id: 'E11B', name:'11-1 雪域密探'},
	            {id: 'E11C', name:'11-1 雪域密探'},
	            {id: 'E12A', name:'11-2 张角余部'},
	            {id: 'E12B', name:'11-2 张角余部'},
	            {id: 'E12C', name:'11-2 张角余部'},
	            {id: 'E13A', name:'11-4 炎族逃兵'},
	            {id: 'E13B', name:'11-4 炎族逃兵'},
	            {id: 'E13C', name:'11-4 炎族逃兵'},
	            {id: 'E14A', name:'11-5 魔化张角'},
	            {id: 'E14B', name:'11-5 魔化张角'},
	            {id: 'E14C', name:'11-5 魔化张角'},
	            {id: 'E15A', name:'11-6 天霜魔军'},
	            {id: 'E15B', name:'11-6 天霜魔军'},
	            {id: 'E15C', name:'11-6 天霜魔军'},
	            {id: 'E16A', name:'11-7 炎帝亲卫'},
	            {id: 'E16B', name:'11-7 炎帝亲卫'},
	            {id: 'E16C', name:'11-7 炎帝亲卫'},
	            {id: 'E17A', name:'11-8 决战炎帝'},
	            {id: 'E17B', name:'11-8 决战炎帝'},
	            {id: 'E17C', name:'11-8 决战炎帝'},
	            {id: 'E21A', name:'12-1 袁军斥候'},
	            {id: 'E21B', name:'12-1 袁军斥候'},
	            {id: 'E21C', name:'12-1 袁军斥候'},
	            {id: 'E22A', name:'12-2 埋伏小兵'},
	            {id: 'E22B', name:'12-2 埋伏小兵'},
	            {id: 'E22C', name:'12-2 埋伏小兵'},
	            {id: 'E23A', name:'12-3 金凤颜良'},
	            {id: 'E23B', name:'12-3 金凤颜良'},
	            {id: 'E23C', name:'12-3 金凤颜良'},
	            {id: 'E24A', name:'12-4 妖灵暗卫'},
	            {id: 'E24B', name:'12-4 妖灵暗卫'},
	            {id: 'E24C', name:'12-4 妖灵暗卫'},
	            {id: 'E25A', name:'12-5 银凰文丑'},
	            {id: 'E25B', name:'12-5 银凰文丑'},
	            {id: 'E25C', name:'12-5 银凰文丑'},
	            {id: 'E26A', name:'12-6 潜行幽魂'},
	            {id: 'E26B', name:'12-6 潜行幽魂'},
	            {id: 'E26C', name:'12-6 潜行幽魂'},
	            {id: 'E27A', name:'12-7 傀儡双子'},
	            {id: 'E27B', name:'12-7 傀儡双子'},
	            {id: 'E27C', name:'12-7 傀儡双子'},
	            {id: 'E31A', name:'13-1 袁尚护卫'},
	            {id: 'E31B', name:'13-1 袁尚护卫'},
	            {id: 'E31C', name:'13-1 袁尚护卫'},
	            {id: 'E32A', name:'13-2 魔化叛军'},
	            {id: 'E32B', name:'13-2 魔化叛军'},
	            {id: 'E32C', name:'13-2 魔化叛军'},
	            {id: 'E33A', name:'13-3 双面袁尚'},
	            {id: 'E33B', name:'13-3 双面袁尚'},
	            {id: 'E33C', name:'13-3 双面袁尚'},
	            {id: 'E34A', name:'13-4 大戟锐士'},
	            {id: 'E34B', name:'13-4 大戟锐士'},
	            {id: 'E34C', name:'13-4 大戟锐士'},
	            {id: 'E35A', name:'13-5 铁甲武卒'},
	            {id: 'E35B', name:'13-5 铁甲武卒'},
	            {id: 'E35C', name:'13-5 铁甲武卒'},
	            {id: 'E36A', name:'13-6 粮仓看守'},
	            {id: 'E36B', name:'13-6 粮仓看守'},
	            {id: 'E36C', name:'13-6 粮仓看守'},
	            {id: 'E37A', name:'13-7 霸主袁绍'},
	            {id: 'E37B', name:'13-7 霸主袁绍'},
	            {id: 'E37C', name:'13-7 霸主袁绍'},
	            {id: 'E41A', name:'14-1 林中埋伏'},
	            {id: 'E41B', name:'14-1 林中埋伏'},
	            {id: 'E41C', name:'14-1 林中埋伏'},
	            {id: 'E42A', name:'14-2 祭祀看守'},
	            {id: 'E42B', name:'14-2 祭祀看守'},
	            {id: 'E42C', name:'14-2 祭祀看守'},
	            {id: 'E43A', name:'14-3 魔女曹节'},
	            {id: 'E43B', name:'14-3 魔女曹节'},
	            {id: 'E43C', name:'14-3 魔女曹节'},
	            {id: 'E44A', name:'14-5 幻影战车'},
	            {id: 'E44B', name:'14-5 幻影战车'},
	            {id: 'E44C', name:'14-5 幻影战车'},
	            {id: 'E45A', name:'14-6 石甲勇士'},
	            {id: 'E45B', name:'14-6 石甲勇士'},
	            {id: 'E45C', name:'14-6 石甲勇士'},
	            {id: 'E46A', name:'14-7 铁刃曹洪'},
	            {id: 'E46B', name:'14-7 铁刃曹洪'},
	            {id: 'E46C', name:'14-7 铁刃曹洪'},
	            {id: 'E51A', name:'15-1 魔族蛮兵'},
	            {id: 'E51B', name:'15-1 魔族蛮兵'},
	            {id: 'E51C', name:'15-1 魔族蛮兵'},
	            {id: 'E52A', name:'15-2 炎化甲兵'},
	            {id: 'E52B', name:'15-2 炎化甲兵'},
	            {id: 'E52C', name:'15-2 炎化甲兵'},
	            {id: 'E53A', name:'15-3 太岁李典'},
	            {id: 'E53B', name:'15-3 太岁李典'},
	            {id: 'E53C', name:'15-3 太岁李典'},
	            {id: 'E54A', name:'15-4 禁地魔影'},
	            {id: 'E54B', name:'15-4 禁地魔影'},
	            {id: 'E54C', name:'15-4 禁地魔影'},
	            {id: 'E55A', name:'15-5 圣器护卫'},
	            {id: 'E55B', name:'15-5 圣器护卫'},
	            {id: 'E55C', name:'15-5 圣器护卫'},
	            {id: 'E56A', name:'15-6 玄甲精锐'},
	            {id: 'E56B', name:'15-6 玄甲精锐'},
	            {id: 'E56C', name:'15-6 玄甲精锐'},
	            {id: 'E57A', name:'15-7 鬼骑夏侯惇'},
	            {id: 'E57B', name:'15-7 鬼骑夏侯惇'},
	            {id: 'E57C', name:'15-7 鬼骑夏侯惇'},
	            {id: 'E61A', name:'16-1 魔族暗哨'},
	            {id: 'E61B', name:'16-1 魔族暗哨'},
	            {id: 'E61C', name:'16-1 魔族暗哨'},
	            {id: 'E62A', name:'16-2 魔族大营'},
	            {id: 'E62B', name:'16-2 魔族大营'},
	            {id: 'E62C', name:'16-2 魔族大营'},
	            {id: 'E63A', name:'16-3 噬血曹真'},
	            {id: 'E63B', name:'16-3 噬血曹真'},
	            {id: 'E63C', name:'16-3 噬血曹真'},
	            {id: 'E64A', name:'16-4 熔岩石晶'},
	            {id: 'E64B', name:'16-4 熔岩石晶'},
	            {id: 'E64C', name:'16-4 熔岩石晶'},
	            {id: 'E65A', name:'16-5 神机木鸢'},
	            {id: 'E65B', name:'16-5 神机木鸢'},
	            {id: 'E65C', name:'16-5 神机木鸢'},
	            {id: 'E66A', name:'16-6 蛊毒药师'},
	            {id: 'E66B', name:'16-6 蛊毒药师'},
	            {id: 'E66C', name:'16-6 蛊毒药师'},
	            {id: 'E67A', name:'16-7 邪刑天徐晃'},
	            {id: 'E67B', name:'16-7 邪刑天徐晃'},
	            {id: 'E67C', name:'16-7 邪刑天徐晃'},
	            {id: 'E71A', name:'17-1'},
	            {id: 'E71B', name:'17-1'},
	            {id: 'E71C', name:'17-1'},
	            {id: 'E72A', name:'17-2'},
	            {id: 'E72B', name:'17-2'},
	            {id: 'E72C', name:'17-2'},
	            {id: 'E73A', name:'17-3'},
	            {id: 'E73B', name:'17-3'},
	            {id: 'E73C', name:'17-3'},
	            {id: 'E74A', name:'17-5'},
	            {id: 'E74B', name:'17-5'},
	            {id: 'E74C', name:'17-5'},
	            {id: 'E75A', name:'17-6'},
	            {id: 'E75B', name:'17-6'},
	            {id: 'E75C', name:'17-6'},
	            {id: 'E76A', name:'17-7'},
	            {id: 'E76B', name:'17-7'},
	            {id: 'E76C', name:'17-7'},
	            {id: 'E81A', name:'18-1'},
	            {id: 'E81B', name:'18-1'},
	            {id: 'E81C', name:'18-1'},
	            {id: 'E82A', name:'18-2'},
	            {id: 'E82B', name:'18-2'},
	            {id: 'E82C', name:'18-2'},
	            {id: 'E83A', name:'18-3'},
	            {id: 'E83B', name:'18-3'},
	            {id: 'E83C', name:'18-3'},
	            {id: 'E84A', name:'18-4'},
	            {id: 'E84B', name:'18-4'},
	            {id: 'E84C', name:'18-4'},
	            {id: 'E85A', name:'18-5'},
	            {id: 'E85B', name:'18-5'},
	            {id: 'E85C', name:'18-5'},
	            {id: 'E86A', name:'18-6'},
	            {id: 'E86B', name:'18-6'},
	            {id: 'E86C', name:'18-6'},
	            {id: 'E87A', name:'18-7'},
	            {id: 'E87B', name:'18-7'},
	            {id: 'E87C', name:'18-7'},
	            {id: 'B01A', name:'3-4 西凉宝藏'},
	            {id: 'B02A', name:'5-3 徐州宝藏'},
	            {id: 'B03A', name:'8-4 下邳宝藏'},
	            {id: 'B04A', name:'11-3 张角宝藏'},
	            {id: 'B05A', name:'14-4 豫州宝藏'},
	            {id: 'B06A', name:'17-4 新野宝藏'},
	            {id: 'J01A', name:'2-7 鬼将华雄'},
	            {id: 'J02A', name:'4-8 尸皇孙坚'},
	            {id: 'J03A', name:'6-7 伪帝袁术'},
	            {id: 'J01B', name:'7-8 巨力岩魔'},
	            {id: 'J02B', name:'9-8 修罗太史慈'},
	            {id: 'J05A', name:'10-8 圣燃炎凤'},
	            {id: 'J04A', name:'12-8 颜良文丑'},
	            {id: 'J04B', name:'13-8 远古剑魂'},
	            {id: 'J05B', name:'15-8 七曜护卫'},
	            {id: 'J03B', name:'16-8 鬼面袁谭'},
	            {id: 'J06A', name:'17-8 斩魂使'},
	            {id: 'J06B', name:'18-8 黑衣隐士'},
	            {id: 'C01A', name:'魔王董卓'},
	            {id: 'C02A', name:'炎龙泰魅'},
	            {id: 'C01B', name:'魔王董卓(困难)'},
	            {id: 'C02B', name:'炎龙泰魅(困难)'},
	            {id: 'C03A', name:'战鬼吕布'},
	            {id: 'C03B', name:'战鬼吕布'},
	            {id: 'I01A', name:'虎牢关大战'},
	            {id: 'I01B', name:'虎牢关大战(困难)'},
	            {id: 'I02A', name:'徐州之战'},
	            {id: 'I02B', name:'徐州之战(困难)'},
	            {id: 'I03A', name:'寿春之战'},
	            {id: 'I03B', name:'寿春之战(困难)'},
	            {id: 'I04A', name:'宛城之战'},
	            {id: 'I04B', name:'宛城之战(困难)'},
	            {id: 'I05A', name:'淮南大战'},
	            {id: 'I05B', name:'淮南大战(困难)'},
	            {id: 'H01A', name:'玄武大阵'},
	            {id: 'H02A', name:'虎牢灭妖'},
	            {id: 'H03A', name:'炼狱塔'},
	            {id: 'H04A', name:'擂台赛'},
	            {id: 'H05A', name:'新擂台赛（废弃）'},
	            {id: 'H06A', name:'秦皇陵'},
	            {id: 'LT01', name:'第1关'},
	            {id: 'LT02', name:'第2关'},
	            {id: 'LT03', name:'第3关'},
	            {id: 'LT04', name:'第4关'},
	            {id: 'LT05', name:'第5关'},
	            {id: 'LT06', name:'第6关'},
	            {id: 'LT07', name:'第7关'},
	            {id: 'LT08', name:'第8关'},
	            {id: 'LT09', name:'第9关'},
	            {id: 'LT10', name:'第10关'},
	            {id: 'LT11', name:'第11关'},
	            {id: 'LT12', name:'第12关'},
	            {id: 'LT13', name:'第13关'},
	            {id: 'LT14', name:'第14关'},
	            {id: 'LT15', name:'第15关'},
	            {id: 'LT16', name:'第16关'},
	            {id: 'LT17', name:'第17关'},
	            {id: 'LT18', name:'第18关'},
	            {id: 'LT19', name:'第19关'},
	            {id: 'LT20', name:'第20关'},
	            {id: 'LT21', name:'第21关'},
	            {id: 'LT22', name:'第22关'},
	            {id: 'LT23', name:'第23关'},
	            {id: 'LT24', name:'第24关'},
	            {id: 'LT25', name:'第25关'},
	            {id: 'LT26', name:'第26关'},
	            {id: 'LT27', name:'第27关'},
	            {id: 'LT28', name:'第28关'},
	            {id: 'LT29', name:'第29关'},
	            {id: 'LT30', name:'第30关'},
	            {id: 'LT31', name:'第31关'},
	            {id: 'LT32', name:'第32关'},
	            {id: 'LT33', name:'第33关'},
	            {id: 'LT34', name:'第34关'},
	            {id: 'LT35', name:'第35关'},
	            {id: 'LT36', name:'第36关'},
	            {id: 'LT37', name:'第37关'},
	            {id: 'LT38', name:'第38关'},
	            {id: 'LT39', name:'第39关'},
	            {id: 'LT40', name:'第40关'},
	            {id: 'LT41', name:'（暂未开放）'},
	            {id: 'LT42', name:'（暂未开放）'},
	            {id: 'LT43', name:'（暂未开放）'},
	            {id: 'LT44', name:'（暂未开放）'},
	            {id: 'LT45', name:'（暂未开放）'},
	            {id: 'LT46', name:'（暂未开放）'},
	            {id: 'LT47', name:'（暂未开放）'},
	            {id: 'LT48', name:'（暂未开放）'},
	            {id: 'LT49', name:'（暂未开放）'},
	            {id: 'LT50', name:'（暂未开放）'},
	            {id: 'LT51', name:'（暂未开放）'},
	            {id: 'LT52', name:'（暂未开放）'},
	            {id: 'LT53', name:'（暂未开放）'},
	            {id: 'LT54', name:'（暂未开放）'},
	            {id: 'LT55', name:'（暂未开放）'},
	            {id: 'LT56', name:'（暂未开放）'},
	            {id: 'LT57', name:'（暂未开放）'},
	            {id: 'LT58', name:'（暂未开放）'},
	            {id: 'LT59', name:'（暂未开放）'},
	            {id: 'LT60', name:'（暂未开放）'},
	            {id: 'LT61', name:'（暂未开放）'},
	            {id: 'LT62', name:'（暂未开放）'},
	            {id: 'LT63', name:'（暂未开放）'},
	            {id: 'LT64', name:'（暂未开放）'},
	            {id: 'LT65', name:'（暂未开放）'},
	            {id: 'LT66', name:'（暂未开放）'},
	            {id: 'LT67', name:'（暂未开放）'},
	            {id: 'LP01', name:'第23关分支'},
	            {id: 'LP02', name:'第40关分支'},
	            {id: 'LP03', name:'（暂未开放）'},
	            {id: 'LP04', name:'（暂未开放）'},
	            {id: 'LP05', name:'（暂未开放）'},
	            {id: 'J001', name:'家园PVE - 第1关'},
	            {id: 'J002', name:'家园PVE - 第2关'},
	            {id: 'J003', name:'家园PVE - 第3关'},
	            {id: 'J004', name:'家园PVE - 第4关'},
	            {id: 'J005', name:'家园PVE - 第5关'},
	            {id: 'J006', name:'家园PVE - 第6关'},
	            {id: 'J007', name:'家园PVE - 第7关'},
	            {id: 'J008', name:'家园PVE - 第8关'},
	            {id: 'J009', name:'家园PVE - 第9关'},
	            {id: 'J010', name:'家园PVE - 第10关'},
	            {id: 'J011', name:'家园PVE - 第11关'},
	            {id: 'J012', name:'家园PVE - 第12关'},
	            {id: 'J013', name:'家园PVE - 第13关'},
	            {id: 'J014', name:'家园PVE - 第14关'},
	            {id: 'J015', name:'家园PVE - 第15关'},
	            {id: 'J016', name:'家园PVE - 第16关'},
	            {id: 'J017', name:'家园PVE - 第17关'},
	            {id: 'J018', name:'家园PVE - 第18关'},
	            {id: 'J019', name:'家园PVE - 第19关'},
	            {id: 'J020', name:'家园PVE - 第20关'},
	            {id: 'J021', name:'家园PVE - 第21关'},
	            {id: 'J022', name:'家园PVE - 第22关'},
	            {id: 'J023', name:'家园PVE - 第23关'},
	            {id: 'J024', name:'家园PVE - 第24关'},
	            {id: 'J025', name:'家园PVE - 第25关'},
	            {id: 'J026', name:'家园PVE - 第26关'},
	            {id: 'J027', name:'家园PVE - 第27关'},
	            {id: 'J028', name:'家园PVE - 第28关'},
	            {id: 'J029', name:'家园PVE - 第29关'},
	            {id: 'J030', name:'家园PVE - 第30关'},
	            {id: 'J031', name:'家园PVE - 第31关'},
	            {id: 'J032', name:'家园PVE - 第32关'},
	            {id: 'J033', name:'家园PVE - 第33关'},
	            {id: 'J034', name:'家园PVE - 第34关'},
	            {id: 'J035', name:'家园PVE - 第35关'},
	            {id: 'J036', name:'家园PVE - 第36关'},
	            {id: 'J037', name:'家园PVE - 第37关'},
	            {id: 'J038', name:'家园PVE - 第38关'},
	            {id: 'J039', name:'家园PVE - 第39关'},
	            {id: 'J040', name:'家园PVE - 第40关'},
	            {id: 'J041', name:'家园PVE - 第41关'},
	            {id: 'J042', name:'家园PVE - 第42关'},
	            {id: 'J043', name:'家园PVE - 第43关'},
	            {id: 'J044', name:'家园PVE - 第44关'},
	            {id: 'J045', name:'家园PVE - 第45关'},
	            {id: 'J046', name:'家园PVE - 第46关'},
	            {id: 'J047', name:'家园PVE - 第47关'},
	            {id: 'J048', name:'家园PVE - 第48关'},
	            {id: 'J049', name:'家园PVE - 第49关'},
	            {id: 'J050', name:'家园PVE - 第50关'},
	            {id: 'J051', name:'家园PVE - 第51关'},
	            {id: 'P01A', name:'虎牢关之战（PVP）'},
	            {id: 'P02A', name:'封炎大战'},
	            {id: 'P02B', name:'PK对冲模式'},
	            {id: 'K101', name:'封炎训练'},
	            {id: 'KA01', name:'封炎训练第1关'},
	            {id: 'KA02', name:'封炎训练第2关'},
	            {id: 'KA03', name:'封炎训练第3关'},
	            {id: 'KA04', name:'封炎训练第4关'},
	            {id: 'P03A', name:'新擂台赛'},
	            {id: 'K107', name:'封炎AI电脑'},
	            {id: 'PJY0', name:'家园攻防战（模拟）'},
	            {id: 'PJY1', name:'家园展示'},
	            {id: 'PJY2', name:'家园战争模拟-老朱用'},
	            {id: 'K001', name:'展示地图'},
	            {id: 'K002', name:'卡牌伤害测试'},
	            {id: 'K003', name:'多人展示地图'},
	            {id: 'K106', name:'军团模型展示'},
	            {id: 'K402', name:'卡牌验证关卡'},
	            {id: 'K102', name:'军团：测试版'},
	            {id: 'K103', name:'军团：模型展示'},
	            {id: 'K104', name:'梦三模型展示'},
	            {id: 'K105', name:'李陈勉测试2'},
	            {id: 'K202', name:'李陈勉测试3'},
	            {id: 'K203', name:'李陈勉测试4'},
	            {id: 'K201', name:'李陈勉测试'},
	            {id: 'K401', name:'秦始皇陵'},
	            {id: 'K301', name:'zpc测试1'},
	            {id: 'PL01', name:'zpc机制测试地图'},
	            {id: 'K302', name:'DPS测试-刘波用'}];
	
	
	function loadMapData() {
		var url = window.location.href.split('?')[0];
		
		var ajaxOption = new Object;
		ajaxOption.dataType = 'JSON';
		ajaxOption.type = 'GET';
		ajaxOption.url = url + '?/open/getMapData';
		ajaxOption.success = function( response ) {
			if( response instanceof Array ) {
				data = response;
			}
		}
		$.ajax( ajaxOption );
	}
	
	loadMapData();	
	
	var EventBase = require( 'eventbase' );
	
	function DataSource() {
		EventBase.call( this );
		
		var getDataByKeyword = function( keyword ) {
			keyword = keyword || '';
			var result = [];
			for( var i = 0; i < data.length; i++ ) {
				var item = data[ i ];
				var id = item.id.toUpperCase();
				var name = item.name;
				if( id.indexOf( keyword.toUpperCase() ) != -1 ) {
					result.push( item );
				} else if( name.indexOf( keyword ) != -1 ) {
					result.push( item );
				}
			}
			
			for( var i = 0; i < result.length; i++ ) {
				item = result[ i ];
				lastLetter = item.id.match( /\w$/ )[ 0 ];
				switch( lastLetter.toUpperCase() ) {
					case 'A':
						item.level = "（普通）";
						break;
					case 'B':
						item.level = '（困难）';
						break;
					case 'C':
						item.level = '（将星）';
						break;
					default:
						item.level = '';
				}
			}
			
			return result;
		}
		
		this.search = function( keyword, callback ) {
			if( typeof( callback ) == 'function' ) {
				var result = getDataByKeyword( keyword );
				callback( result );
			}
		}
	}
	module.exports = DataSource;
} );